# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZTQxYjhkMDE1ZTk1NDY2N2NiMWE2YWU0NDcxZWRjNmE1ZGQ4NjIyNDI3NmM2YzJkMWFhYTQzZTQ0NWM3MmRmNTkxMDZlMjdkMTNhNjdlZjczYmYwYThlYzNmOTdhYzlmNzQxMmUyYmEzY2M1MmFkNGJkZDQxMmQ2NjdjYjMzN2U=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
